sudo: required
services:
  - docker

before_install:
  - docker build  -t infopcn/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run infopcn/react-test npm test -- --coverage

after_success:
  - docker build -t infopcn/multi-client ./client
  - docker build -t infopcn/multi-nginx ./nginx
  - docker build -t infopcn/multi-server ./server
  - docker build -t infopcn/multi-worker ./worker
  #log in the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
      # LES variables ci-dessus sont configurées dans travis-ci

  # prendre ces images et les push sur dockerhub
  - docker push infopcn/multi-client
  - docker push infopcn/multi-nginx
  - docker push infopcn/multi-server
  - docker push infopcn/multi-worker