sudo: required
services:
  - docker

before_install:
  - docker build -t lcarlosTest/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run lcarlosTest/react-test npm test -- --coverage

after_success:
  - docker build -t lcarlosTest/multi-client ./client
  - docker build -t lcarlosTest/multi-nginx ./nginx
  - docker build -t lcarlosTest/multi-server ./server
  - docker build -t lcarlosTest/multi-worker ./worker
  #log in the docker CLI
# - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
      # LES variables ci-dessus sont configurées dans travis-ci

  # prendre ces images et les push sur dockerhub
#  - docker push lcarlosTest/multi-client
#  - docker push lcarlosTest/multi-nginx
#  - docker push lcarlosTest/multi-server
#  - docker push lcarlosTest/multi-worker